name: Worflow Netflix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 0. Configurar credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuración de Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # 3. Instalar dependencias
    - name: NPM Install & Build
      run: |
        npm install
        npm run build

    # 4. Zippear el build
    - name: Zippear el build
      run: |
        zip -r build.zip build/*

    # 6. Subir el archivo ZIP a S3
    - name: Subir a S3
      run: |
        aws s3 cp build.zip s3://netflix-build-039612858559/
